"""
Kids B2-B5 (L11-L50): word formation → sentences → stories → final.
Master plan kids course (50 lessons, 5 blocks of 10):
  B1: Знакомство (1-10) ✓ done
  B2: Word formation (11-20)
  B3: Sentences (21-30)
  B4: Stories (31-40)
  B5: Mastery + final (41-50)
Target WPM: 18→50. Mentor: Klavochka (warm, fairy-tale tone, very encouraging).
Style: simple words, animals/colors/food/family themes, short repetitions.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'data' / 'lessons' / 'en_kids'


def lesson(num, title, desc, wpm, text, keys, focus, tips, char_tips,
           phase=2, rhythm=False, error_pct=10):
    text_len = len(text)
    return {
        "id": f"en_kids_lesson_{num:02d}",
        "tier": "en_kids",
        "lesson_number": num,
        "title": title,
        "description": desc,
        "target_wpm": wpm,
        "text_length": text_len,
        "error_limit_percent": error_pct,
        "error_limit": max(2, int(text_len * error_pct / 100)),
        "text": text,
        "text_sequence": [],
        "keys_trained": keys,
        "new_keys": [],
        "finger_focus": focus,
        "tips": tips,
        "character_tips": char_tips,
        "phase": phase,
        "rhythmLesson": rhythm,
        "created_at": "2026-05-25",
        "version": "1.0"
    }


# === KIDS BLOCK 2 (L11-20) — Word formation, more letters ===
B2 = [
    lesson(11, "Letters E and I",
           "Two new letters — E and I",
           19, "e e e i i i see see see is is is if if if eel eel ice ice tie tie",
           ["E","I","A-Z"],
           "Top row letters E and I",
           ["E is left middle finger reaching UP",
            "I is right middle finger reaching UP",
            "Try \"see\" — a fun new word!"],
           {"anna": "Two new letters: E and I. New words like \"see\"!",
            "maxim": "Two more letters online. Words expanding.",
            "knopych": "🤖 E AND I! New buttons!",
            "klavochka": "Two new friends, my dear — E and I 💕"}),

    lesson(12, "Letters O and U",
           "More letters — O and U",
           20, "o o o u u u up up up out out out you you you sun sun fun fun cup cup",
           ["O","U","A-Z"],
           "Top row O and U",
           ["O is right ring finger UP",
            "U is right index UP",
            "Now you can write \"you\" and \"sun\"!"],
           {"anna": "O and U. Now you can write \"you\" — say hello to someone!",
            "maxim": "Vowels online. Words multiply fast.",
            "knopych": "🤖 O AND U! Even MORE buttons!",
            "klavochka": "Sunshine letters, my sweet — O and U ☀️"}),

    lesson(13, "Letters T and N",
           "Important letters — T and N",
           21, "t t t n n n the the the an an an in in in on on on not not not tan tan",
           ["T","N","A-Z"],
           "T and N",
           ["T is left index UP",
            "N is right index DOWN",
            "\"the\" is the most common word in English"],
           {"anna": "T and N. \"The\" is used EVERYWHERE — type it lots!",
            "maxim": "T and N = top frequency letters. Vital.",
            "knopych": "🤖 T AND N! Super important!",
            "klavochka": "Two strong letters, my treasure 💪"}),

    lesson(14, "Common 3-letter words",
           "Tiny words you can read",
           22, "the cat sat on a mat the dog ran fast the sun was hot a fish in the sea a bee on a tree",
           ["A-Z","Space"],
           "Word formation",
           ["Real little sentences!",
            "Each tiny word is just 2-3 letters",
            "Spaces with your thumb"],
           {"anna": "Look — real sentences! Tiny words, big meaning.",
            "maxim": "Word formation begins. Reading + typing together.",
            "knopych": "🤖 TINY SENTENCES! Real reading!",
            "klavochka": "Little stories, my sunshine 🌸"}),

    lesson(15, "Rhythm: 3-letter words",
           "Repeat words with a steady beat",
           22, "cat cat cat dog dog dog see see see run run run fun fun fun the the the and and and yes yes yes",
           ["A-Z","Space"],
           "Rhythm with words",
           ["Same word three times = practice",
            "Like a song, my dear",
            "Steady beat with your fingers"],
           {"anna": "Words like song verses — three times each.",
            "maxim": "Repetition + rhythm = muscle memory.",
            "knopych": "🥁 RHYTHM TIME! Same words, steady beat!",
            "klavochka": "Like a little song, my dear 🎶"},
           rhythm=True),

    lesson(16, "Colors: red, blue, green",
           "Color words!",
           23, "red red red blue blue blue green green green yellow yellow pink pink black black white white",
           ["A-Z","Space"],
           "Color vocabulary",
           ["Six colors!",
            "Picture each color while you type",
            "Memory loves pictures"],
           {"anna": "Colors! Picture them as you type.",
            "maxim": "Color vocabulary. Image-anchored words.",
            "knopych": "🌈 RAINBOW MODE! Color collector!",
            "klavochka": "All the pretty colors, my dear 🌈"}),

    lesson(17, "Foods: apple, milk, cake",
           "Yummy food words!",
           24, "apple milk cake bread egg honey juice rice cheese banana pizza soup carrot lemon plum",
           ["A-Z","Space"],
           "Food vocabulary",
           ["Tasty words!",
            "Foods are friendly to picture",
            "Type each one twice in your mind"],
           {"anna": "Foods! Imagine them as you type each word.",
            "maxim": "Food vocab. Easy to picture, easy to remember.",
            "knopych": "🍎 SNACK TIME! Food words on the menu!",
            "klavochka": "Yummy little words, my treasure 🍰"}),

    lesson(18, "Family: mom, dad, sister",
           "Family words",
           24, "mom dad sister brother grandma grandpa aunt uncle baby cousin friend pet love family home",
           ["A-Z","Space"],
           "Family vocabulary",
           ["Family is the best!",
            "Each word is someone you love",
            "Picture their face as you type"],
           {"anna": "Family words. Each one is special.",
            "maxim": "Family vocab. High personal connection = better memory.",
            "knopych": "👨‍👩‍👧 FAMILY UNLOCKED! Love mode!",
            "klavochka": "Words full of love, my dear 💕"}),

    lesson(19, "Pre-final: little sentences",
           "Small sentences before the milestone",
           25, "i see a cat the dog runs fast my mom is kind the sun is hot we eat cake i love you",
           ["A-Z","Space"],
           "Pre-milestone sentences",
           ["Tiny sentences in flow",
            "Speed test before block end",
            "No capitals or punctuation yet — just words"],
           {"anna": "Little sentences! Almost a story.",
            "maxim": "Pre-milestone test. Word fluency check.",
            "knopych": "📚 ALMOST READY! Block 2 finale next!",
            "klavochka": "So close to the next milestone, my dear ⭐"}),

    lesson(20, "BLOCK 2 FINAL: First short story",
           "First real story at 25 WPM",
           25, "a cat sat on the mat. the dog came in. the cat ran fast. the dog ran too. they played in the yard. mom called them home. the end.",
           ["A-Z","Space",".",","],
           "Block 2 mastery gate",
           ["🎉 First real story!",
            "Period at the end of each sentence",
            "You're a real little writer now!"],
           {"anna": "🎯 First story! 25 WPM = great young typist.",
            "maxim": "Block 2 done. Word formation mastered.",
            "knopych": "🐉 BLOCK 2 BOSS DEFEATED! Real story written!",
            "klavochka": "🎉 First story, my hero! 💖 So proud!"}),
]

# === KIDS BLOCK 3 (L21-30) — Sentences + punctuation + numbers ===
B3 = [
    lesson(21, "Capital letters and periods",
           "Big letters and little dots",
           26, "I see a cat. The dog runs. Mom is here. Dad is too. We are home. It is fun. The sun is hot.",
           ["A-Z","Shift","Space","."],
           "Sentences with capitals",
           ["Big letter starts a sentence",
            "Period ends a sentence",
            "Shift + letter = big letter"],
           {"anna": "Capital letters at sentence starts. Period at the end.",
            "maxim": "Sentences need structure. Capitals and periods.",
            "knopych": "🤖 BIG LETTERS! Press Shift first!",
            "klavochka": "Big letters like proud kings, my dear 👑"},
           phase=3),

    lesson(22, "First questions",
           "Ask things — questions have a curly mark!",
           27, "Is it red? Do you see? Where is mom? What is that? Why is it hot? How are you? Who is here?",
           ["A-Z","Shift","Space","?"],
           "Questions with ?",
           ["Questions end with ?",
            "? is Shift + / on the right side",
            "Always start with capital"],
           {"anna": "Questions end with ?. Type Shift + / to get it!",
            "maxim": "Question mark — Shift + slash. Always with capital start.",
            "knopych": "❓ ASK MODE! Question marks unlocked!",
            "klavochka": "Curious questions, my dear ❓💕"},
           phase=3),

    lesson(23, "Exclamations with !",
           "Excited sentences — wow!",
           28, "Wow! That is fun! Look at me! I did it! Yay! I love it! That is so cool! Great job!",
           ["A-Z","Shift","Space","!"],
           "Excited sentences with !",
           ["! is Shift + 1 — top row left!",
            "Used for excitement",
            "Always capital at start"],
           {"anna": "Excitement! Use ! when you're happy or surprised!",
            "maxim": "Exclamation mark. Shift + 1.",
            "knopych": "🎉 WOW MODE! Excitement unlocked!",
            "klavochka": "Happy sentences, my treasure! 🎉"},
           phase=3),

    lesson(24, "Three sentence kinds together",
           "Mix it all — period, question, excitement",
           29, "I see a cat. Is it black? Yes! Look at it run. Wow! Where does it go? It goes home. The end!",
           ["A-Z","Shift","Space",".","?","!"],
           "All three sentence endings",
           ["Statements end with .",
            "Questions end with ?",
            "Excitement ends with !"],
           {"anna": "Three sentence kinds. Each has its own ending.",
            "maxim": "Three sentence endings. Practice mixing them.",
            "knopych": "🎯 TRIPLE MIX! Three sentence types!",
            "klavochka": "All three friends together, my dear 💖"},
           phase=3),

    lesson(25, "25-lesson milestone",
           "Halfway through the kids course!",
           30, "I can type. I can read what I type. I write sentences. I ask questions. I share happy news. I am a little writer now! Yay!",
           ["A-Z","Shift","Space",".","!"],
           "Halfway milestone",
           ["🎉 Halfway done!",
            "You are a real little writer",
            "25 more lessons to your certificate"],
           {"anna": "🎯 Halfway, little friend! You're doing AMAZING.",
            "maxim": "25 lessons in. Halfway. Solid foundation.",
            "knopych": "🏔️ HALFWAY UP THE MOUNTAIN! Look back, look proud!",
            "klavochka": "Halfway to your crown, my sunshine ⭐⭐"},
           phase=3),

    lesson(26, "Numbers 1 to 5",
           "Count with numbers!",
           30, "1 2 3 4 5 one two three four five 12345 one apple two cats three dogs four bees five stars",
           ["1","2","3","4","5","A-Z","Space"],
           "Number row left side",
           ["Numbers are at the TOP of the keyboard",
            "Use the same finger as the letter below",
            "1 = left pinky, 2 = ring, etc."],
           {"anna": "Numbers! Use the same finger as the letter below.",
            "maxim": "Left number row. Same fingers as QWERT column.",
            "knopych": "🔢 COUNT! 1, 2, 3, 4, 5!",
            "klavochka": "Counting up like steps, my dear 🪜"},
           phase=3),

    lesson(27, "Numbers 6 to 10",
           "Bigger numbers!",
           31, "6 7 8 9 10 six seven eight nine ten 678910 six bees seven cats eight dogs nine fish ten kids",
           ["6","7","8","9","0","A-Z","Space"],
           "Number row right side",
           ["6 = right index, 0 = right pinky",
            "Same fingers as YUIOP",
            "Numbers + words mix"],
           {"anna": "Right side numbers. Mirror of left side.",
            "maxim": "Full number row. 10 digits now.",
            "knopych": "🔢 COUNT MORE! 6, 7, 8, 9, 10!",
            "klavochka": "All the way to ten, my star ⭐"},
           phase=3),

    lesson(28, "Rhythm: counting song",
           "Number song with a steady beat",
           32, "1 little 2 little 3 little stars 4 little 5 little 6 little stars 7 little 8 little 9 little stars 10 stars in the sky",
           ["0-9","A-Z","Space"],
           "Number + word rhythm",
           ["Number song!",
            "Like a counting rhyme",
            "Steady beat with your fingers"],
           {"anna": "Number song! Steady beat as you count.",
            "maxim": "Numbers + words rhythm. Mixed-content practice.",
            "knopych": "🎵 COUNT-SONG! Number rhythm!",
            "klavochka": "Singing while counting, my dear 🎶"},
           phase=3, rhythm=True),

    lesson(29, "Pre-final: numbers in stories",
           "Numbers mixed in real little stories",
           32, "I have 3 cats and 2 dogs. We saw 5 birds. There are 10 stars. Mom baked 4 cakes. I read 6 books today!",
           ["A-Z","0-9","Shift","Space",".","!"],
           "Mixed numbers + sentences",
           ["Numbers + sentences together",
            "All character types in flow",
            "Pre-final test"],
           {"anna": "Numbers IN stories. Real life writing.",
            "maxim": "Pre-final test. Real content density.",
            "knopych": "🎯 ALMOST AT BOSS! Numbers + stories!",
            "klavochka": "Real little story with numbers, my dear 🌟"},
           phase=3),

    lesson(30, "BLOCK 3 FINAL: Story with sentences",
           "Real story with all three sentence kinds at 32 WPM",
           32, "I have 2 cats. They love to play! Where do they go all day? They climb trees. They chase bees. They sleep in the sun. I love my 2 cats so much!",
           ["A-Z","0-9","Shift","Space",".","?","!"],
           "Block 3 mastery gate",
           ["🎉 Real story with all three sentence kinds!",
            "Numbers too!",
            "32 WPM = great young typist"],
           {"anna": "🎯 Block 3 done! Real story with all sentence types!",
            "maxim": "Block 3 cleared. Sentences mastered.",
            "knopych": "🐉 BLOCK 3 BOSS DEFEATED! Sentence mastery!",
            "klavochka": "🎉 Three blocks done! My hero! ⭐⭐⭐"},
           phase=3),
]

# === KIDS BLOCK 4 (L31-40) — Short stories, fairy tales ===
B4 = [
    lesson(31, "Animal adventure: part 1",
           "First real story chapter",
           33, "Once upon a time there was a little fox. The fox lived in a big forest. Every day the fox played with his friends. They ran and laughed all day long!",
           ["A-Z","Shift","Space",".","!"],
           "Story chapter 1",
           ["Block 4 = real stories!",
            "Multi-sentence flow",
            "Picture the fox as you type"],
           {"anna": "Block 4! Real stories. Picture each scene as you type.",
            "maxim": "Story structure: setup + character + action.",
            "knopych": "📚 STORY MODE! Adventure begins!",
            "klavochka": "Once upon a time, my dear 🌸 Listen and type!"},
           phase=4),

    lesson(32, "Animal adventure: part 2",
           "Story continues!",
           34, "One day the little fox got lost. He was scared. He looked for his friends. He called and called. Then he saw a tree he knew. He ran home and found his family!",
           ["A-Z","Shift","Space",".","!"],
           "Story chapter 2",
           ["Story has problem + solution",
            "Multi-sentence emotional flow",
            "Picture the fox finding home"],
           {"anna": "Stories have problems and solutions. Picture each part.",
            "maxim": "Narrative arc in practice. Story-typing trains both skills.",
            "knopych": "📚 PLOT TWIST! Fox gets lost — and FOUND!",
            "klavochka": "Such a happy ending, my dear 💖"},
           phase=4),

    lesson(33, "Rhythm: animal song",
           "Cute animal song with rhythm",
           34, "the little fox the little fox jumps and runs jumps and runs the happy bear the happy bear sings a song sings a song",
           ["A-Z","Space"],
           "Song-like rhythm",
           ["A song you can clap along to",
            "Repeating phrases = rhythm",
            "Steady beat as you type"],
           {"anna": "Animal song. Tap a rhythm with your fingers.",
            "maxim": "Song-rhythm practice. Pattern repetition.",
            "knopych": "🎵 ANIMAL SONG! Jump-jump-sing-sing!",
            "klavochka": "A song about animals, my sunshine 🎶🦊"},
           phase=4, rhythm=True),

    lesson(34, "Princess and dragon",
           "Classic fairy tale start",
           35, "Once there was a kind princess. She had a tiny pet dragon. The dragon was scared of mice! The princess gave him hugs. The dragon felt brave again.",
           ["A-Z","Shift","Space",".","!"],
           "Fairy tale rhythm",
           ["Princess + dragon = classic fairy tale",
            "Reversal: dragon scared of mice (funny!)",
            "Picture the princess and her dragon"],
           {"anna": "Fairy tale! Princess saves the dragon — fun reversal.",
            "maxim": "Fairy tale structure. Classic narrative training.",
            "knopych": "🏰 FAIRY TALE! Brave princess, tiny dragon!",
            "klavochka": "A magical story, my dear 🐲👸"},
           phase=4),

    lesson(35, "35-lesson milestone",
           "Five lessons to the next block!",
           36, "35 lessons! You read and write stories now. You ask questions. You count to ten. You are a real writer! Only 15 lessons left to your big certificate!",
           ["A-Z","0-9","Shift","Space",".","!"],
           "35-lesson speed test",
           ["🎉 You're a real writer now!",
            "15 lessons to the certificate",
            "Block 5 will have a big finale"],
           {"anna": "🎯 35 lessons! Real writer status. 15 to the finale!",
            "maxim": "35 in. Final block has 15 more. Pace yourself.",
            "knopych": "🏆 35! Almost at the top!",
            "klavochka": "15 steps to your crown, my hero 👑"},
           phase=4),

    lesson(36, "Day at school",
           "A normal day at school",
           37, "I go to school at 8 in the morning. We read books. We sing songs. We play games at lunch time. After school I run home to mom and dad. I love school days!",
           ["A-Z","0-9","Shift","Space",".","!"],
           "Daily life story",
           ["Real-life story with time",
            "Numbers in context (8 morning)",
            "Daily routine writing"],
           {"anna": "Daily life story. Numbers fit naturally with words.",
            "maxim": "Routine writing. Real-world content.",
            "knopych": "🏫 SCHOOL DAY! From morning to home!",
            "klavochka": "A whole school day, my dear 📚"},
           phase=4),

    lesson(37, "Best friend story",
           "Story about a friend",
           38, "My best friend is named Lily. She has a tiny puppy named Sam. We play in the park every Sunday. We share snacks. We laugh a lot. She makes every day fun!",
           ["A-Z","Shift","Space",".","!"],
           "Personal narrative",
           ["Personal story with names",
            "Names with capitals (Lily, Sam)",
            "Personal narrative tone"],
           {"anna": "Best friend story. Names need capital letters.",
            "maxim": "Personal narrative. Capitals + emotion.",
            "knopych": "👫 BEST FRIEND! Lily and Sam!",
            "klavochka": "A story about love, my dear 💕"},
           phase=4),

    lesson(38, "Birthday party",
           "Birthday celebration!",
           39, "Today is my birthday! I am 8 years old. Mom made a big cake with 8 candles. My friends came over. We played games. I got a new bike. Best day ever!",
           ["A-Z","0-9","Shift","Space",".","!"],
           "Celebration story",
           ["Age numbers mixed with words",
            "Excited tone (lots of !)",
            "Personal happy story"],
           {"anna": "Birthday story! Excitement with lots of !",
            "maxim": "Celebration prose. Mixed content + emotion.",
            "knopych": "🎂 BIRTHDAY MODE! Cake, candles, presents!",
            "klavochka": "Happy birthday, my dear 🎉🎂"},
           phase=4),

    lesson(39, "Pre-final: full story",
           "Almost-final story practice",
           40, "Once upon a time in a small house there lived a brave little mouse. He helped his friends. He shared his food. He told funny stories. Everyone loved him. The end!",
           ["A-Z","Shift","Space",".","!"],
           "Pre-final story",
           ["Full story arc",
            "Multi-sentence flow at 40 WPM",
            "Last warmup before block final"],
           {"anna": "Full mini-story. Like the block final, but easier.",
            "maxim": "Pre-final story. Multi-sentence narrative speed.",
            "knopych": "📖 ONE STORY TO RULE THEM ALL — almost!",
            "klavochka": "Such a sweet story, my hero 🐭💕"},
           phase=4),

    lesson(40, "BLOCK 4 FINAL: Fairy tale",
           "Block 4 final — a complete fairy tale at 40 WPM",
           40, "There once was a tiny dragon named Pip. Pip was small but had a HUGE heart. He helped lost kittens find their homes. He gave hugs to sad bunnies. He sang songs at night. Every animal in the forest loved Pip very much. The end!",
           ["A-Z","Shift","Space",".","!"],
           "Block 4 mastery gate",
           ["🎉 Full fairy tale!",
            "All capital uses included",
            "Block 5 brings the certificate exam!"],
           {"anna": "🎯 Block 4 done! Real fairy tale written!",
            "maxim": "Block 4 cleared. Story mastery achieved.",
            "knopych": "🐉 BLOCK 4 BOSS DEFEATED! Story master!",
            "klavochka": "🎉 Four blocks, my hero! ⭐⭐⭐⭐"},
           phase=4),
]

# === KIDS BLOCK 5 (L41-50) — Mastery + final ===
B5 = [
    lesson(41, "All animals together",
           "Many animals in one passage",
           42, "Cats and dogs and birds and bees. Foxes, bears, and busy ants. Rabbits hop, and turtles crawl. Fish swim in the sea below. All the animals make the world fun!",
           ["A-Z","Shift","Space",".",","],
           "Animal vocabulary at speed",
           ["Block 5 — mastery and final coming!",
            "Lots of animal words in flow",
            "Picture each animal as you type"],
           {"anna": "Block 5! All your animal friends together.",
            "maxim": "Vocabulary review at speed. Image-anchored prose.",
            "knopych": "🦊🐻🐰 ANIMAL PARADE!",
            "klavochka": "Every animal you love, my sunshine 💕"},
           phase=5),

    lesson(42, "All colors together",
           "A rainbow in writing",
           42, "Red apples and blue skies. Green grass and yellow sun. Purple flowers and pink hearts. Black night and white snow. Colors make the world beautiful!",
           ["A-Z","Shift","Space",".","!"],
           "Color vocabulary at speed",
           ["All colors in real sentences",
            "Picture each color + object",
            "Beautiful word painting"],
           {"anna": "Colors in real sentences. Word painting!",
            "maxim": "Color-image pairing. Memory-strong content.",
            "knopych": "🌈 RAINBOW SHOWCASE!",
            "klavochka": "Such a colorful world, my treasure 🌈"},
           phase=5),

    lesson(43, "My favorite things",
           "Personal favorites list",
           43, "I love sunny days. I love my family. I love books and music. I love cookies and ice cream. I love playing outside. I love sleeping in too! What do you love?",
           ["A-Z","Shift","Space",".","!","?"],
           "Personal preferences at speed",
           ["Personal love list",
            "Multiple sentence types",
            "Real personal writing"],
           {"anna": "Favorites list! What do YOU love?",
            "maxim": "Personal preference writing. High engagement.",
            "knopych": "❤️ LOVE LIST! All the things!",
            "klavochka": "Sharing what makes you happy, my dear 💝"},
           phase=5),

    lesson(44, "Long story practice",
           "A longer story — sustained focus",
           44, "Once there was a girl named Maya who loved to read. Every night she read a book under the covers with a tiny flashlight. One night the book started to glow! Inside was a tiny world with tiny people. Maya was their hero from then on. She visited every night.",
           ["A-Z","Shift","Space",".","!"],
           "Long story",
           ["Longer story = sustained focus",
            "Multiple plot beats",
            "Practice for the finale"],
           {"anna": "Long story practice. Focus across multiple sentences.",
            "maxim": "Sustained narrative speed. Pre-finale conditioning.",
            "knopych": "📖 EPIC TALE! Maya's adventures!",
            "klavochka": "A magical reading adventure, my dear 📚✨"},
           phase=5),

    lesson(45, "45-lesson milestone",
           "Five lessons to the certificate!",
           45, "45 lessons! You can write real stories, ask questions, count numbers, and share your feelings. Five lessons left until you become a certified little typist. Stay calm, type with care!",
           ["A-Z","0-9","Shift","Space",".","!",","],
           "45-lesson speed test",
           ["🎉 Five lessons left!",
            "Real typing skill achieved",
            "Finale at L50 — the certificate!"],
           {"anna": "🎯 45 in! Five to the certificate. Stay calm.",
            "maxim": "45 lessons. Five to finale. Hold the gain.",
            "knopych": "🏆 5 TO GO! Certificate incoming!",
            "klavochka": "Five steps to your special crown, my hero 👑"},
           phase=5),

    lesson(46, "Numbers + letters mixed",
           "Mix everything",
           46, "I have 4 pets, 12 books, and 8 best friends. My grandma is 65. She makes 24 cookies every Sunday at 3 in the afternoon. Life is full of numbers and good things!",
           ["A-Z","0-9","Shift","Space",".",","],
           "All content classes mixed",
           ["Numbers + words flowing",
            "Multiple sentence types",
            "All you've learned, all at once"],
           {"anna": "Numbers and words flowing together. Real life!",
            "maxim": "Mixed content at 46 WPM. Pre-final density.",
            "knopych": "🎯 ALL THE THINGS! Mixed mode!",
            "klavochka": "Numbers and stories together, my dear 🌟"},
           phase=5),

    lesson(47, "Rhythm: full alphabet song",
           "Sing the alphabet with a steady beat",
           47, "a b c d e f g h i j k l m n o p q r s t u v w x y z next time wont you sing with me a b c d e f g",
           ["A-Z","Space"],
           "Alphabet song rhythm",
           ["The ABC song!",
            "Every letter in song form",
            "Sing along in your head"],
           {"anna": "ABC song! Sing in your head, type with your fingers.",
            "maxim": "Alphabet song = full keyboard at song tempo.",
            "knopych": "🎵 A-B-C SONG! Sing it loud!",
            "klavochka": "Our favorite song, my sunshine 🎶"},
           phase=5, rhythm=True),

    lesson(48, "Pre-final mix",
           "Last big mix before the certificate exam",
           48, "I write stories, I count to 10, I love my family, and I have 3 pets named Max, Coco, and Bear. My favorite color is red. My favorite food is pizza. What is yours?",
           ["A-Z","0-9","Shift","Space",".",",","?"],
           "Pre-final density",
           ["All content classes",
            "Real conversational writing",
            "Last drill before the certificate"],
           {"anna": "Pre-final drill. Two lessons to certificate!",
            "maxim": "All content classes at 48 WPM. Pre-final.",
            "knopych": "📝 PRE-CERT DRILL! 2 to go!",
            "klavochka": "Almost at the certificate, my dear 🎓"},
           phase=5),

    lesson(49, "Final warmup",
           "Calm focus before the big finish",
           49, "One lesson left, my little hero. Take a breath. Sit up tall. Place your fingers on home row. Find F and J by feel. The next lesson is your certificate exam. You can do it!",
           ["A-Z","Shift","Space",".",",","!"],
           "Final warmup",
           ["Calming meta-prose",
            "One lesson to the certificate",
            "Confidence + readiness"],
           {"anna": "Last warmup. Breathe. You've trained for this.",
            "maxim": "Final warmup. Body and mind ready.",
            "knopych": "⚔️ FINAL BOSS NEXT! Hands ready!",
            "klavochka": "One breath away from your crown, my hero 👑🌸"},
           phase=5),

    lesson(50, "KIDS COURSE FINAL: My adventure",
           "The final exam — 50 WPM on a complete adventure story. Pass earns the Kids Mastery certificate!",
           50, "Once there was a brave little kid who wanted to learn to type. They started with just one letter. Then two. Then ten. Then they could write stories, ask questions, and count to a hundred! After 50 lessons, they earned the title of Real Typist. That brave kid is YOU. Yay!",
           ["A-Z","0-9","Shift","Space",".","!"],
           "Kids course comprehensive exam",
           ["🎓 KIDS COURSE FINAL!",
            "Pass at 25+ WPM = Bronze, 40+ = Silver",
            "After this you are CERTIFIED!",
            "Type slowly if you must — accuracy first"],
           {"anna": "🎓🏆 KIDS FINAL! 50 lessons led here. Type with care!",
            "maxim": "End of kids course. Pass = certified.",
            "knopych": "🐉👑 FINAL BOSS! Crown the little hero!",
            "klavochka": "🎉🎉🎉 My hero, the final moment! 👑✨ Crown earned!"},
           phase=5, error_pct=8),
]


ALL = B2 + B3 + B4 + B5
for d in ALL:
    fp = OUT / f'lesson_{d["lesson_number"]:02d}.json'
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print(f'  wrote en_kids/lesson_{d["lesson_number"]}.json ({d["text_length"]} chars, WPM {d["target_wpm"]})')

print(f'\nDone. {len(ALL)} kids B2-B5 lessons generated. Kids course COMPLETE.')
