"""
Teen B2 (L16-L30): Top/Bottom rows + pop culture content.
Master plan: «БЛОК 2: Расширение (16-30) — Верхний и нижний ряды,
Соревнования на время. Тексты: Песни, диалоги из сериалов».
Target WPM: 38→55. Mentor: Knopych.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'data' / 'lessons' / 'en_teen'
OUT.mkdir(parents=True, exist_ok=True)


def lesson(num, title, desc, wpm, text, keys, focus, tips, char_tips,
           phase=2, rhythm=False, error_pct=7):
    text_len = len(text)
    return {
        "id": f"en_teen_lesson_{num:02d}",
        "tier": "en_teen",
        "lesson_number": num,
        "title": title,
        "description": desc,
        "target_wpm": wpm,
        "text_length": text_len,
        "error_limit_percent": error_pct,
        "error_limit": max(3, int(text_len * error_pct / 100)),
        "text": text,
        "text_sequence": [],
        "keys_trained": keys,
        "new_keys": [],
        "finger_focus": focus,
        "tips": tips,
        "character_tips": char_tips,
        "phase": phase,
        "rhythmLesson": rhythm,
        "created_at": "2026-05-25",
        "version": "1.0"
    }


LESSONS = [
    lesson(16, "Top row mastery: Q W E R T",
           "Drill left top row at speed — focus on accuracy",
           38, "we wet were quit quiet rate water write quote query trade weather quest quartz tweet rest start great",
           ["Q","W","E","R","T","A-Z","Space"],
           "Left top row precision",
           ["Same finger as A-S-D-F column but UP",
            "Q is left pinky — uncommon but still needs speed",
            "Return to home row between bursts"],
           {"anna": "Top row left. Stretch up, then HOME. Repeat.",
            "maxim": "QWERT bottlenecks are common. Drill them flat now.",
            "knopych": "TOP ROW LEFT! ⬆️ Reach high — and back home!",
            "klavochka": "Up and down like waves, my dear 🌊"}),

    lesson(17, "Top row mastery: Y U I O P",
           "Right top row at speed",
           40, "you our up yo top join trip pop play opera union youth point coupon junior trophy story open jury",
           ["Y","U","I","O","P","A-Z","Space"],
           "Right top row precision",
           ["P is right pinky — practice it specifically",
            "Y is right index reach UP",
            "Common letters here — drill at speed"],
           {"anna": "Right top row. Pinky P is the trickiest — give it extra attention.",
            "maxim": "YUIOP completes top row. Pros never look at these keys.",
            "knopych": "TOP ROW RIGHT! ⬆️🟢 Pinky-P powered up!",
            "klavochka": "All your right finger friends up high, my sunshine 🌟"}),

    lesson(18, "Top row mixed sprint",
           "Both hands top row at speed",
           42, "type writer poetry quiet quote weather report quarter try water power try writer poet point quote",
           ["Q","W","E","R","T","Y","U","I","O","P","Space"],
           "Both hands top row",
           ["Hand alternation = speed booster",
            "Most English uses TY-RE-WE-OP patterns",
            "Notice your hands trading off"],
           {"anna": "Hand alternation = natural speed. Feel both hands trading off.",
            "maxim": "Top row mixed = real-world speed test.",
            "knopych": "BOTH HANDS UP! ⬆️⬆️ Tag team!",
            "klavochka": "Hands taking turns, my treasure 🤝"}),

    lesson(19, "Bottom row: Z X C V B",
           "Left hand DOWN — bottom row drill",
           43, "ax cab vex back zap five six box brave cave maze brand cracks branch chance basic black break",
           ["Z","X","C","V","B","A-Z","Space"],
           "Left bottom precision",
           ["DOWN from home — curl fingers under",
            "Z and X are rare but still need speed",
            "C and V appear in everyday words"],
           {"anna": "Curl fingers UNDER your palm to reach down. Less awkward over time.",
            "maxim": "Bottom row is most ergonomically awkward — drill until it's natural.",
            "knopych": "BOTTOM ROW LEFT! ⬇️ Curl 'em fingers!",
            "klavochka": "Bending down like picking berries, my dear 🍓"}),

    lesson(20, "Bottom row: N M",
           "Right hand bottom — N and M complete the alphabet",
           45, "now man and number money name come name common manual ninja announce mention amount among nominate",
           ["N","M","A-Z","Space"],
           "Right bottom + frequent letters",
           ["N and M = right index + middle finger DOWN",
            "Most common bottom-row letters",
            "All 26 letters under your fingers now"],
           {"anna": "N and M finish the alphabet. Every letter at your speed now.",
            "maxim": "Full alphabet at 45 WPM. From here, all gains are practice.",
            "knopych": "ALL 26 LETTERS! 🔓 Full keyboard unlocked at speed!",
            "klavochka": "Every letter your dear friend, my sunshine ☀️"}),

    lesson(21, "Rhythm: alphabet song",
           "Pangram-style flow at sustained tempo",
           46, "the quick brown fox jumps over the lazy dog while five wizards jinx my big quartz vow today and tomorrow",
           ["A-Z","Space",","],
           "Full alphabet rhythm",
           ["Two pangrams back to back — every letter at least once",
            "Metronome at 46 BPM — match it",
            "Don't slow at rare letters — keep the tempo"],
           {"anna": "Every letter in flow. Find the rhythm and don't drop it.",
            "maxim": "Pangram flow = full keyboard rhythm test.",
            "knopych": "ALPHABET SONG! 🎵 All letters dancing!",
            "klavochka": "All letters singing together, my dear 🎶"},
           phase=2, rhythm=True),

    lesson(22, "Movie quotes drill",
           "Iconic movie lines at speed",
           47, "May the Force be with you. I'll be back. To infinity and beyond! Why so serious? With great power comes great responsibility.",
           ["A-Z","Shift","Space","'",".","!","?"],
           "Capitals + punctuation in real lines",
           ["Iconic movie quotes — already in your memory",
            "Mix of statements, exclamations, questions",
            "Shift timing matters — practice the entry"],
           {"anna": "Movie lines you already know. Type by memory, not by sight.",
            "maxim": "Pop culture phrases live in muscle memory long after the movie.",
            "knopych": "🎬 BLOCKBUSTER MODE! Quotes you live by!",
            "klavochka": "Lines from beloved movies, my treasure 🎞️"}),

    lesson(23, "Song lyrics: chorus repetition",
           "Repeating chorus structure — rhythm of song",
           48, "shine shine shine on shine shine shine on we are young we are gold we will never grow old shine shine shine on",
           ["A-Z","Space"],
           "Song-chorus repetition rhythm",
           ["Choruses repeat for a reason — train muscle memory",
            "Type along to a beat in your head",
            "Speed comes from rhythm, not effort"],
           {"anna": "Song lyrics are repetition by design — perfect for typing speed.",
            "maxim": "Chorus structure = pattern recognition for fingers.",
            "knopych": "🎤 SING-ALONG MODE! Chorus on repeat!",
            "klavochka": "Like singing in the shower, my sunshine 🚿🎵"}),

    lesson(24, "TV dialogue snippet",
           "Show-style banter at speed",
           49, "Hey, did you see that? No way! That was epic. Wait, what's happening now? Just watch. Trust me on this one, okay?",
           ["A-Z","Shift","Space",".",",","?","!","'"],
           "Dialogue rhythm + multiple punctuation",
           ["TV banter is short, snappy, real",
            "Multiple speakers = quick punctuation shifts",
            "Practice the comma+space+capital pattern"],
           {"anna": "Real-world dialogue. Short, punctuated, fast.",
            "maxim": "TV writing is the high-density end of dialogue. Master this.",
            "knopych": "📺 SCRIPT MODE! Two characters arguing at speed!",
            "klavochka": "Friends talking on a show, my dear 💬"}),

    lesson(25, "Mid-block speed sprint",
           "Pure speed — common short words",
           50, "we are the best and we know it now is the time to shine and show the world we can do this together as one",
           ["A-Z","Space"],
           "Short common words at speed",
           ["No punctuation = pure rhythm",
            "All home/top row friendly words",
            "Push past 50 WPM here"],
           {"anna": "Pure speed test. No tricks — just words at top tempo.",
            "maxim": "Sprint training. Don't slow for any reason.",
            "knopych": "⚡ SPEED MODE! No brakes! GO GO GO!",
            "klavochka": "Like racing, my star — fast but light 🌟"}),

    lesson(26, "Capitals: pop culture names",
           "Real names from movies, games, music",
           51, "Marvel DC Pixar Disney Netflix Spotify TikTok YouTube Instagram Nintendo PlayStation Xbox Tesla SpaceX Apple Google",
           ["A-Z","Shift","Space"],
           "Capital letters + brand names",
           ["Pop culture brands — capitals everywhere",
            "Shift timing must be smooth",
            "Brand names = real-world capital practice"],
           {"anna": "Brand names test your Shift timing under real-world content.",
            "maxim": "Capitals are 5% of all writing. Drill until automatic.",
            "knopych": "🎮 BRAND PARADE! All your favorites!",
            "klavochka": "Names everyone knows, my dear 📱"}),

    lesson(27, "Numbers: gaming stats",
           "Game-style numbers + words",
           52, "Level 99 max HP 1500 EXP 24000 won 12 lost 3 streak 7 rank 42 score 9876 kills 18 K/D 2.5 winrate 65 percent",
           ["A-Z","0-9","Space","/","."],
           "Numbers in real context",
           ["Gaming stats = numbers + text mixed",
            "Numbers should flow as fast as letters by now",
            "Slash and decimal are fluid"],
           {"anna": "Gaming stats are pure number+word mixing. Real teen vocab.",
            "maxim": "Numbers in context — better than isolated digit drills.",
            "knopych": "🎮 GAMER STATS! Numbers like a pro player!",
            "klavochka": "Counting the wins, my hero 🏆"}),

    lesson(28, "Rhythm: song lyrics paragraph",
           "Full lyric verse at sustained tempo",
           53, "tonight we own the city lights tonight we make the rules tonight we never close our eyes tonight we never lose",
           ["A-Z","Space"],
           "Sustained song-lyric rhythm",
           ["Multi-line lyric verse — find the song-like rhythm",
            "Metronome at 53 BPM",
            "Speed comes from feel, not effort"],
           {"anna": "Lyric verse at full speed. Sing along in your head.",
            "maxim": "Lyrics = sustained rhythm at higher WPM. Real test.",
            "knopych": "🎵 ANTHEM MODE! Sing it like you mean it!",
            "klavochka": "A whole song verse, my sunshine 🎶"},
           phase=2, rhythm=True),

    lesson(29, "Competition prep: speed drill",
           "Mixed real-world content — pre-final warmup",
           54, "Hey team, the tournament starts at 7 sharp. Bring your A-game, your headphones, and stay focused. We've trained for this — let's win it together!",
           ["A-Z","0-9","Shift","Space",".",",","!","-","'"],
           "Mixed content pre-final",
           ["All character classes — letters, digit, punctuation",
            "Realistic team message style",
            "Last warmup before BLOCK 2 FINAL"],
           {"anna": "Real teen team-message style. One step before the final.",
            "maxim": "Pre-final warmup. Mixed content at near-final speed.",
            "knopych": "🏆 TOURNAMENT INCOMING! Final prep!",
            "klavochka": "Almost at the next milestone, my dear ⭐"}),

    lesson(30, "BLOCK 2 FINAL: Extension mastery",
           "Block 2 final — 55 WPM on a pop-culture-flavored paragraph",
           55, "Last night's stream hit 50K viewers — biggest yet! Big thanks to the squad, the mods, and everyone who showed up. Next session: Saturday at 8 PM. Drop a follow if you're new, and let's keep this energy going!",
           ["A-Z","0-9","Shift","Space",".",",","!","-","'",":"],
           "Block 2 mastery gate at 55 WPM",
           ["🎓 Teen Block 2 done! 55 WPM = mid-course teen pro speed",
            "From here, Block 3 brings numbers + symbols + emoji-style writing",
            "If you missed by a few WPM, retry — accuracy first, speed second"],
           {"anna": "🎯 Teen Block 2 done! 55 WPM = top-of-class. Block 3 next.",
            "maxim": "Extension mastery cleared. From here, real-world applied speed.",
            "knopych": "🐉🏆 BLOCK 2 BOSS DOWN! Extension mastered!",
            "klavochka": "Second triumph, my hero! 🎉⭐⭐ Onward!"},
           error_pct=6),
]


for d in LESSONS:
    fp = OUT / f'lesson_{d["lesson_number"]:02d}.json'
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print(f'  wrote en_teen/lesson_{d["lesson_number"]}.json ({d["text_length"]} chars, WPM {d["target_wpm"]})')

print(f'\nDone. {len(LESSONS)} Teen B2 lessons generated.')
