"""
Teen B5 (L61-L75): Practice — school + essays + final tournament.
Master plan: «БЛОК 5: Практика (61-75) — Школьные задания, Рефераты и эссе,
Финал: Турнир и сертификат».
Target WPM: 86→95. Mentor: Knopych.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'data' / 'lessons' / 'en_teen'


def lesson(num, title, desc, wpm, text, keys, focus, tips, char_tips,
           phase=5, rhythm=False, error_pct=4):
    text_len = len(text)
    return {
        "id": f"en_teen_lesson_{num:02d}",
        "tier": "en_teen",
        "lesson_number": num,
        "title": title,
        "description": desc,
        "target_wpm": wpm,
        "text_length": text_len,
        "error_limit_percent": error_pct,
        "error_limit": max(3, int(text_len * error_pct / 100)),
        "text": text,
        "text_sequence": [],
        "keys_trained": keys,
        "new_keys": [],
        "finger_focus": focus,
        "tips": tips,
        "character_tips": char_tips,
        "phase": phase,
        "rhythmLesson": rhythm,
        "created_at": "2026-05-25",
        "version": "1.0"
    }


LESSONS = [
    lesson(61, "School assignment: introduction",
           "Real school assignment opening at speed",
           86, "In this essay, I will examine the role of social media in shaping how teenagers communicate, learn, and form their identity, with a focus on both the positive and negative impacts seen over the past five years.",
           ["A-Z","Shift","Space",".",",","-"],
           "Essay intro rhythm",
           ["Block 5 = practical school work",
            "Essay opening = thesis + scope",
            "Hold 86 WPM through long sentences"],
           {"anna": "Block 5 — real school writing. This is what you'll type for years.",
            "maxim": "Essay introductions are a daily-life format. Train them well.",
            "knopych": "📚 SCHOOL MODE! Essay assault begins!",
            "klavochka": "Sharing what you know with words, my dear 📖"}),

    lesson(62, "Essay paragraph: body",
           "Argument paragraph with examples",
           87, "One clear example of this trend is the rise of short-form video platforms, which have transformed not only entertainment but also how students study, share information, and even apply for jobs in the modern workplace.",
           ["A-Z","Shift","Space",".",",","-"],
           "Body paragraph rhythm",
           ["Argument structure: claim + example + impact",
            "Long flowing sentences",
            "Real essay tempo"],
           {"anna": "Body paragraph structure. Real essay format at speed.",
            "maxim": "Argument prose = your real writing voice. Train it.",
            "knopych": "📝 ESSAY POWER! Make the point!",
            "klavochka": "Building a strong argument, my treasure 🏛️"}),

    lesson(63, "Literary analysis snippet",
           "Book analysis with quoted phrases",
           88, "The author uses repetition as a powerful tool. Phrases like \"the wind kept blowing\" appear in three separate chapters, suggesting that nature itself becomes a character in the novel.",
           ["A-Z","Shift","Space",".",",","\"","'"],
           "Literary analysis rhythm",
           ["Quotes inside analysis = high-density format",
            "Mid-sentence quoted phrases",
            "Real literature class writing"],
           {"anna": "Literary analysis. Quotes inside argument = pro-level English.",
            "maxim": "Book analysis is the highest-skill school writing.",
            "knopych": "📚 BOOK BREAKDOWN! Analysis mode!",
            "klavochka": "Discovering the secrets of a book, my dear 🔍"}),

    lesson(64, "Science report paragraph",
           "Lab report style with measurements",
           89, "The experiment was conducted at 25 degrees Celsius using a 100 ml sample. After 30 minutes, the reaction reached equilibrium with a pH of 7.4. Three trials confirmed the result, with a standard deviation of 0.08.",
           ["A-Z","0-9","Shift","Space",".",",","°"],
           "Scientific writing rhythm",
           ["Science writing = facts + numbers + precision",
            "Decimals, units, terminology",
            "Highest-density real school content"],
           {"anna": "Science writing. Highest-density school content.",
            "maxim": "Lab reports test mixed-content speed under accuracy.",
            "knopych": "🧪 LAB REPORT! Numbers and findings!",
            "klavochka": "Sharing what experiments reveal, my dear 🔬"}),

    lesson(65, "65-lesson milestone",
           "Two-thirds of teen course — checkpoint",
           90, "65 lessons. You can write a school essay faster than you can think it. That's a real skill. The remaining ten lessons polish what you have, and then you'll face the final tournament-style exam at lesson 75.",
           ["A-Z","Shift","Space",".",",","-"],
           "65-lesson speed test",
           ["90 WPM = top 5% globally for any age",
            "Ten lessons to teen course final",
            "L75 is the tournament exam"],
           {"anna": "🎯 90 WPM. Top 5% in the world. Ten lessons to the final tournament.",
            "maxim": "65 in. Final stretch. Hold the gain.",
            "knopych": "🏆 65! TOURNAMENT INCOMING!",
            "klavochka": "Ten steps to the throne, my hero 👑"}),

    lesson(66, "History essay paragraph",
           "Historical narrative with dates",
           90, "By 1969, the moon landing had captured the imagination of the entire world. Nearly 600 million people watched live on television. The mission demonstrated what was possible when nations invested in long-term, ambitious goals.",
           ["A-Z","0-9","Shift","Space",".",",","-"],
           "History writing rhythm",
           ["History = dates + names + narrative",
            "Long sentences with embedded facts",
            "School-essay realism"],
           {"anna": "History essay format. Dates and narrative in flow.",
            "maxim": "History writing = storytelling with anchors. Train it.",
            "knopych": "🚀 HISTORY MODE! Moon landing facts!",
            "klavochka": "Stories of the past, my dear 📜"}),

    lesson(67, "Rhythm: essay flow",
           "Multi-sentence essay at sustained tempo",
           91, "The question, then, is not whether change will come — it always does — but how we respond to it. Adapting requires courage. Adapting well requires both courage and curiosity. Together, these two qualities define every generation that has ever shaped the future.",
           ["A-Z","Shift","Space",".",",","—","-"],
           "Essay flow at 91 WPM",
           ["Sustained essay tempo with em-dashes",
            "Three sentences in one rhythm",
            "Metronome at 91 BPM"],
           {"anna": "Essay flow at 91 WPM. Real academic speed.",
            "maxim": "Multi-sentence essay = sustained pro speed.",
            "knopych": "📝 ESSAY FLOW! Argument cascade!",
            "klavochka": "Wisdom flowing in sentences, my sunshine 🌟"},
           phase=5, rhythm=True),

    lesson(68, "Book review",
           "Real book review style",
           92, "What makes this novel special isn't the plot — it's the way the author trusts her readers to fill in the spaces between the lines. Some chapters end on questions, not answers. That choice alone is worth the read.",
           ["A-Z","Shift","Space",".",",","—","'"],
           "Review rhythm + opinion",
           ["Book review = analysis + opinion blend",
            "Em-dashes for emphasis mid-sentence",
            "Real Goodreads/blog format"],
           {"anna": "Book review style. Real online writing format.",
            "maxim": "Reviews are mid-density opinion writing.",
            "knopych": "📖 BOOK REVIEW! Five-star analysis!",
            "klavochka": "Sharing a book's beauty, my treasure ⭐"}),

    lesson(69, "Research notes",
           "Quick research-note style — facts + sources",
           93, "Source 1 (Nature, 2024): The fastest typing speed recorded is 216 WPM, set in 1946 on a manual typewriter. Source 2 (Guinness): Modern computer-typing record is 248 WPM. Both rely on extensive muscle-memory training over years.",
           ["A-Z","0-9","Shift","Space",".",",","(",")",":",";"],
           "Research note rhythm",
           ["Note format = source + fact + parens",
            "High-density factual prose",
            "Real research workflow"],
           {"anna": "Research notes. Highest-density factual format.",
            "maxim": "If you can type research at 93 WPM, papers fly by.",
            "knopych": "🔬 RESEARCH MODE! Sources locked!",
            "klavochka": "Notes from learning, my dear 📚"}),

    lesson(70, "70-lesson milestone",
           "Pre-final checkpoint at 93 WPM",
           93, "Five lessons remain. You can type 93 words per minute on dense school content — most adults can't. The final, at lesson 75, is a tournament-style mixed-content paragraph. Stay sharp, stay accurate, finish strong.",
           ["A-Z","Shift","Space",".",",","-"],
           "70-lesson speed test",
           ["93 WPM on school content = elite teen",
            "5 lessons to final tournament exam",
            "L75 is the certificate exam"],
           {"anna": "🎯 93 WPM. Five lessons left. Don't peak early — hold steady.",
            "maxim": "70 in. Five to finish. Hold the gain.",
            "knopych": "🏆 5 TO GO! Last sprint!",
            "klavochka": "Five steps to your crown, my hero ⭐"}),

    lesson(71, "Pre-tournament drill",
           "Speed drill at near-tournament pace",
           94, "Tournament prep: type without thinking, scan ahead by two words, breathe normally, and let your fingers do what they've trained to do for 70 lessons. Numbers, names, punctuation — all in the same rhythm.",
           ["A-Z","Shift","Space",".",",","-",";"],
           "Tournament prep",
           ["Tournament rhythm at 94 WPM",
            "Mental prep is half the win",
            "Practice the headspace"],
           {"anna": "Tournament prep. Mental + physical rhythm.",
            "maxim": "Pre-tournament drill. Calibrate your pace.",
            "knopych": "🏆 PRE-TOURNAMENT! Calm fingers, focused mind!",
            "klavochka": "Breathing and preparing, my dear 🌬️"}),

    lesson(72, "Rhythm: literary passage",
           "Sustained literary prose at 94 WPM",
           94, "She walked down the long hallway in silence, past the closed doors and the photographs of people she had never met. At the end of the corridor, the door to the garden stood slightly open, letting in the soft afternoon light.",
           ["A-Z","Shift","Space",",","."],
           "Literary rhythm at 94 WPM",
           ["Long literary sentence at 94 WPM",
            "Imagery + flow without breaks",
            "Metronome at 94 BPM"],
           {"anna": "Literary prose at 94 WPM. Beautiful and fast.",
            "maxim": "Literature at this speed = professional novelist territory.",
            "knopych": "📖 LITERARY FLOW! Beautiful and fast!",
            "klavochka": "Like a beautiful story unfolding, my sunshine 🌷"},
           phase=5, rhythm=True),

    lesson(73, "Tournament-prep dense paragraph",
           "Maximum-density content at high speed",
           95, "Q2 2026 stats are in: 12.4M new users (+47% YoY), 89% activation rate, ARR at $215M, NPS of 72. Top markets: US (38%), EU (29%), APAC (24%). Next milestone: Series D by Q4. Read the full report at company.com/q2-2026.",
           ["A-Z","0-9","Shift","Space",".",",","(",")","%","+","$","-",":","/"],
           "Maximum density",
           ["Highest-density mixed content",
            "Numbers, symbols, percentages, URL",
            "Last warmup before tournament final"],
           {"anna": "Maximum density. Pre-final exam intensity.",
            "maxim": "All character classes at 95 WPM. Real work pace.",
            "knopych": "📊 DATA FLOOD! All the numbers!",
            "klavochka": "Every kind of character at speed, my star ⭐"}),

    lesson(74, "Final warmup: real-world prose",
           "One step before the tournament — flowing prose",
           95, "One lesson to go. You've come a long way: from finding F and J by feel, to writing essays faster than most adults can think them. Take a breath. The next lesson is a comprehensive exam — pass it for the Teen Mastery certificate.",
           ["A-Z","Shift","Space",".",",","-",":"],
           "Final warmup",
           ["Encouraging meta-prose at 95 WPM",
            "Smooth steady rhythm",
            "Confidence before the boss"],
           {"anna": "One lesson left. Breathe. You've trained for this.",
            "maxim": "Final warmup. Hands ready, mind calm.",
            "knopych": "⚔️ FINAL BOSS NEXT! Last warmup!",
            "klavochka": "One step from the throne, my hero 👑"}),

    lesson(75, "TEEN COURSE FINAL: Tournament + certificate",
           "The final teen exam — 95 WPM on a comprehensive mixed real-world paragraph. Pass earns the Teen Mastery certificate.",
           95, "Seventy-five lessons ago, the keyboard was a puzzle. Today, it's an extension of your thinking. You can write essays in minutes, send messages faster than you can speak, and keep up with any deadline. This final paragraph — 350 characters, 95 WPM, mixed content — is the gate. Pass it, and the Teen Mastery certificate is yours. Type with care.",
           ["A-Z","0-9","Shift","Space",".",",","-",":","'"],
           "Teen mastery comprehensive exam",
           ["🎓 TEEN COURSE FINAL — 95 WPM, 350 chars",
            "Pass at 60+ WPM = Gold cert, 80+ = Platinum",
            "After this you are CERTIFIED teen typist",
            "Type slowly if you must — accuracy gates cert level"],
           {"anna": "🎓🏆 TEEN FINAL. 75 lessons led here. Type with care — certificate is one paragraph away.",
            "maxim": "End of teen course. Pass = certified for life. Slow + steady wins.",
            "knopych": "🐉👑 FINAL BOSS! ONE LAST FIGHT FOR THE CROWN!",
            "klavochka": "My hero, final moment! Breathe, type, earn your crown 👑✨"},
           error_pct=4),
]


for d in LESSONS:
    fp = OUT / f'lesson_{d["lesson_number"]:02d}.json'
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print(f'  wrote en_teen/lesson_{d["lesson_number"]}.json ({d["text_length"]} chars, WPM {d["target_wpm"]})')

print(f'\nDone. {len(LESSONS)} Teen B5 lessons generated. Teen course COMPLETE.')
