"""
Teen B4 (L46-L60): Speed sprints + news/blogs/forums.
Master plan: «БЛОК 4: Скорость (46-60) — Быстрые спринты. Тексты: Новости, блоги, форумы».
Target WPM: 72→85. Mentor: Knopych.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'data' / 'lessons' / 'en_teen'


def lesson(num, title, desc, wpm, text, keys, focus, tips, char_tips,
           phase=4, rhythm=False, error_pct=5):
    text_len = len(text)
    return {
        "id": f"en_teen_lesson_{num:02d}",
        "tier": "en_teen",
        "lesson_number": num,
        "title": title,
        "description": desc,
        "target_wpm": wpm,
        "text_length": text_len,
        "error_limit_percent": error_pct,
        "error_limit": max(3, int(text_len * error_pct / 100)),
        "text": text,
        "text_sequence": [],
        "keys_trained": keys,
        "new_keys": [],
        "finger_focus": focus,
        "tips": tips,
        "character_tips": char_tips,
        "phase": phase,
        "rhythmLesson": rhythm,
        "created_at": "2026-05-25",
        "version": "1.0"
    }


LESSONS = [
    lesson(46, "3-letter word sprint",
           "Most common 3-letter words at speed",
           72, "the and you for not but get had has him her our out one new now nor say see she sit way who why yes off",
           ["A-Z","Space"],
           "3-letter words rhythm",
           ["Block 4 opens with pure speed",
            "3-letter words = single hand-shift units",
            "No thinking — pure muscle memory"],
           {"anna": "Block 4! Speed first. 3-letter words = the rhythm engine.",
            "maxim": "Top common words. Drill until automatic.",
            "knopych": "⚡ SPEED MODE! 3-letter combo attack!",
            "klavochka": "Tiny words flying fast, my dear 🦋"}),

    lesson(47, "4-letter word sprint",
           "Most common 4-letter words at speed",
           74, "that with this have from they will know also like into back over make most year well take time many",
           ["A-Z","Space"],
           "4-letter words rhythm",
           ["4-letter words = bigger units, still snappy",
            "Watch for 'th' bigrams — should be one motion",
            "Type ahead — read 1-2 words past your cursor"],
           {"anna": "4-letter words. Read ahead — your fingers know the next ones.",
            "maxim": "Read 1-2 words ahead. Pro pattern.",
            "knopych": "⚡ 4-CHAR BURST! Bigger combos!",
            "klavochka": "Waves of words, my sunshine 🌊"}),

    lesson(48, "Bigram burst: th in er an re",
           "Top bigrams as single motions",
           75, "th in er an re or at en nd te he as on of nt to ti is it ar st al de be ng wh ch ed",
           ["A-Z","Space"],
           "Bigram speed",
           ["These bigrams = 20% of all English",
            "Each pair = ONE motion, not two",
            "If a pair feels slow, drill it 10x"],
           {"anna": "Bigrams are speed building blocks. Pair = motion.",
            "maxim": "Top bigrams. Single units in your muscle memory.",
            "knopych": "⚡ BIGRAM SPEED! Two keys, ONE attack!",
            "klavochka": "Letter couples dancing together, my dear 💑"}),

    lesson(49, "News headline drill",
           "Quick news headlines at speed",
           76, "Tech giant announces layoffs. Stocks slip on weak data. New album breaks streaming record. Climate deal signed in Geneva today.",
           ["A-Z","Shift","Space",".",","],
           "Headline rhythm",
           ["Headlines = short, punchy, fact-rich",
            "Capitals at sentence start — Shift practice",
            "Each headline ends with period — clean break"],
           {"anna": "Headline style. Short, punchy, capitals + facts.",
            "maxim": "News headlines = high-density information at speed.",
            "knopych": "📰 NEWSROOM! Headlines firing!",
            "klavochka": "Important news of the day, my dear 📺"}),

    lesson(50, "50-lesson teen milestone",
           "Two-thirds through teen course",
           75, "fifty lessons done and your fingers are flying. the next 25 lessons turn this speed into sustainable habit. dont stop now — momentum is everything in this part of the journey.",
           ["A-Z","Space",",",".","-"],
           "50-lesson speed test",
           ["50 = two-thirds of teen course",
            "Track your peak — should be 70+ by now",
            "Final block (B5) takes you to 90+"],
           {"anna": "🎯 50 lessons in! Two-thirds done. Final stretch coming.",
            "maxim": "Halfway+? Track your peak. Final block is application.",
            "knopych": "🏁 50! HOMESTRETCH MODE!",
            "klavochka": "Two-thirds to legend, my star ⭐⭐"}),

    lesson(51, "Blog excerpt",
           "Personal blog passage at speed",
           78, "I've been thinking a lot about productivity lately. Not the kind that involves five apps and color-coded calendars — just the simple kind: do the thing, then do the next thing.",
           ["A-Z","Shift","Space",".",",","-","'"],
           "Blog prose rhythm",
           ["Blog style = conversational, mid-length sentences",
            "Em-dashes and apostrophes are common",
            "Real personal-writing rhythm"],
           {"anna": "Blog prose. Conversational, real-world, mid-density.",
            "maxim": "Blog writing is the most-typed long-form content. Train it.",
            "knopych": "📝 BLOG MODE! Personal voice at speed!",
            "klavochka": "Like a friend's diary, my dear 📖"}),

    lesson(52, "Forum thread reply",
           "Multi-paragraph forum reply",
           80, "honestly i had the same problem last year. what worked for me was just stepping back, focusing on one thing at a time, and not trying to fix everything in a week. small wins add up faster than you think.",
           ["A-Z","Space",",",".","-"],
           "Forum reply rhythm",
           ["Forum prose = lowercase, conversational, long-ish",
            "Multiple commas in flow — match the tempo",
            "Reddit/HN style realism"],
           {"anna": "Forum-thread style. Real online conversation rhythm.",
            "maxim": "Forum replies = mid-density daily prose.",
            "knopych": "💬 FORUM REPLY! Wisdom drop!",
            "klavochka": "Sharing what worked, my sunshine 💡"}),

    lesson(53, "Rhythm: news flow",
           "News paragraph at sustained tempo",
           80, "Markets opened higher on Friday after positive earnings reports from three major tech firms. Analysts pointed to strong cloud growth and resilient consumer demand. The rally is expected to extend into next week.",
           ["A-Z","Shift","Space",",",".","Apos"],
           "News paragraph at speed",
           ["Multi-sentence news at 80 WPM",
            "Metronome at 80 BPM — match it",
            "Sustained journalism speed"],
           {"anna": "News flow at 80 WPM. Newsroom speed.",
            "maxim": "Multi-sentence news = real journalist daily speed.",
            "knopych": "📰 LIVE FROM NEWSROOM! 80 WPM!",
            "klavochka": "Reporting the world at speed, my dear 🌍"},
           phase=4, rhythm=True),

    lesson(54, "Trending topics commentary",
           "Quick takes on trending topics",
           81, "Hot take: streaming services are stagnating, AI music is everywhere now, and the best content lives on small creators with under 50K followers. The big platforms know it. Question is what they'll do about it.",
           ["A-Z","Shift","Space",".",",","'",":"],
           "Commentary writing rhythm",
           ["Punchy opinion writing format",
            "Numbers + punctuation + capitals mixed",
            "Quick observational prose"],
           {"anna": "Hot-take commentary. Modern opinion writing format.",
            "maxim": "Commentary at high speed = think-and-type fluency.",
            "knopych": "🔥 HOT TAKE MODE! Opinion blazing!",
            "klavochka": "Sharing fresh thoughts, my treasure 💭"}),

    lesson(55, "Speed challenge: quick draft",
           "Type a quick draft message at speed",
           83, "Hey team, just got off the call with the client. They want to push launch by two weeks and add the new feature we discussed. Can we sync at 4 today to plan? Quick chat — 15 minutes max.",
           ["A-Z","Shift","Space",".",",","-","?","'"],
           "Draft message at speed",
           ["Real team-message style at 83 WPM",
            "Numbers + punctuation + flow",
            "Practice writing what you would actually send"],
           {"anna": "Quick team message. Real work pace.",
            "maxim": "Draft writing at 83 WPM = pro speed for daily work.",
            "knopych": "📨 QUICK MESSAGE! Ship it fast!",
            "klavochka": "Sending a message quickly, my dear ✉️"}),

    lesson(56, "Multi-paragraph news article",
           "Full news article at sustained pace",
           83, "Scientists in Vienna announced on Monday a major breakthrough in quantum sensor technology. The discovery, detailed in Nature, could reshape medical imaging within the decade. Industry partners are already lining up to license the work.",
           ["A-Z","Shift","Space",",","."],
           "Article rhythm",
           ["Real journalism: facts + names + dates + flow",
            "Hold 83 WPM across all sentences",
            "Article rhythm = newsroom standard"],
           {"anna": "Real journalism. Sustained 83 WPM across full article.",
            "maxim": "News articles are the gold standard of prose density.",
            "knopych": "📰 FULL ARTICLE! Breaking news!",
            "klavochka": "A whole story in one paragraph, my sunshine 📰"}),

    lesson(57, "Tech blog snippet",
           "Tech writer style with terms",
           84, "We migrated from Postgres to a custom solution last quarter. The trade-offs surprised us. Queries are 3x faster, but ops overhead grew. Looking back, would I do it again? Honestly, yes — but with way more upfront planning.",
           ["A-Z","Shift","Space",".",",","?","-","'","x"],
           "Tech blog rhythm",
           ["Tech terms + opinion + multiple punctuation",
            "Conversational technical writing",
            "Real engineering blog pattern"],
           {"anna": "Tech blog style. Engineers write more than they code.",
            "maxim": "Technical commentary at 84 WPM. Real career skill.",
            "knopych": "💻 TECH BLOG! Devs writing about devs!",
            "klavochka": "A coder telling a story, my dear ⚙️"}),

    lesson(58, "Rhythm: forum thread flow",
           "Multiple forum replies stitched together",
           85, "good point but i'd argue the opposite. agree to disagree but here's why i think differently. interesting take though never thought of it that way. fair enough lets just move on then.",
           ["A-Z","Space",",",".","'"],
           "Forum thread rhythm",
           ["Multiple voices in flow — chat-like",
            "Lowercase intentional, apostrophes everywhere",
            "Metronome at 85 BPM"],
           {"anna": "Forum thread rhythm. Multiple voices, one tempo.",
            "maxim": "Online debate prose at 85 WPM.",
            "knopych": "💬 FORUM DEBATE! Multiple takes!",
            "klavochka": "Friends debating thoughtfully, my dear 🤔"},
           phase=4, rhythm=True),

    lesson(59, "Pre-final: high-speed mixed",
           "Mixed content at near-final teen speed",
           85, "Q3 numbers just dropped — revenue +28%, users +14%, retention at 91%. Team meeting at 3 PM in conference room B. Bring your laptops, your questions, and your best ideas for Q4.",
           ["A-Z","0-9","Shift","Space",".",",","%","-","+","'",":"],
           "Pre-final mix",
           ["All character classes at 85 WPM",
            "Real work-message density",
            "Last warmup before BLOCK 4 FINAL"],
           {"anna": "Pre-final mix. Pass = ready for L60 boss.",
            "maxim": "All character classes at 85 WPM = pro work speed.",
            "knopych": "📊 STATS DROP! All the data!",
            "klavochka": "Business message at speed, my star ⭐"}),

    lesson(60, "BLOCK 4 FINAL: Speed mastery",
           "Block 4 final — 85 WPM on a real news/blog hybrid passage",
           85, "After eighteen months of beta testing, the platform officially launched on Monday with over 200,000 sign-ups in the first 24 hours. Early reviews from creators have been overwhelmingly positive: \"This finally feels like a tool built by people who actually use it,\" wrote one popular reviewer. Investors are watching closely.",
           ["A-Z","0-9","Shift","Space",".",",","\"","-",":"],
           "Block 4 final gate at 85 WPM",
           ["🎓 Teen Block 4 done! 85 WPM on real news/blog",
            "From here, Block 5 = practical school + final exam",
            "L75 is the course final at 95 WPM"],
           {"anna": "🎯 Teen Block 4 done! 85 WPM. Final block coming.",
            "maxim": "Speed mastery cleared. Block 5 = real-world application.",
            "knopych": "🐉🏆 BLOCK 4 BOSS DOWN! Speed elite!",
            "klavochka": "Four triumphs, my hero! 🎉⭐⭐⭐⭐"},
           error_pct=4),
]


for d in LESSONS:
    fp = OUT / f'lesson_{d["lesson_number"]:02d}.json'
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print(f'  wrote en_teen/lesson_{d["lesson_number"]}.json ({d["text_length"]} chars, WPM {d["target_wpm"]})')

print(f'\nDone. {len(LESSONS)} Teen B4 lessons generated.')
