"""
Teen B3 (L31-L45): Numbers + Emoji + Internet slang.
Master plan: «БЛОК 3: Цифры и символы (31-45) — Эмодзи и интернет-сленг,
Социальные сети стиль. Тексты: Твиты, посты, комментарии».
Target WPM: 56→70. Mentor: Knopych.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'data' / 'lessons' / 'en_teen'


def lesson(num, title, desc, wpm, text, keys, focus, tips, char_tips,
           phase=3, rhythm=False, error_pct=6):
    text_len = len(text)
    return {
        "id": f"en_teen_lesson_{num:02d}",
        "tier": "en_teen",
        "lesson_number": num,
        "title": title,
        "description": desc,
        "target_wpm": wpm,
        "text_length": text_len,
        "error_limit_percent": error_pct,
        "error_limit": max(3, int(text_len * error_pct / 100)),
        "text": text,
        "text_sequence": [],
        "keys_trained": keys,
        "new_keys": [],
        "finger_focus": focus,
        "tips": tips,
        "character_tips": char_tips,
        "phase": phase,
        "rhythmLesson": rhythm,
        "created_at": "2026-05-25",
        "version": "1.0"
    }


LESSONS = [
    lesson(31, "Numbers left: 1-5 at speed",
           "Drill left-hand digits — same fingers as Q-W-E-R-T",
           56, "1 2 3 4 5 12 23 34 45 15 25 35 45 11 22 33 44 55 12345 54321 11223 33445 12121",
           ["1","2","3","4","5","Space"],
           "Left number row",
           ["Numbers row is the FAR stretch — same finger as column letter",
            "1=pinky, 2=ring, 3=middle, 4=index, 5=index reach",
            "Don't look at the number row"],
           {"anna": "Numbers row is far. Same finger as the column letter — that's the rule.",
            "maxim": "Main row digits, not numpad. The latter is a different skill.",
            "knopych": "🔢 LEFT DIGITS! 1-5 same fingers as QWERT!",
            "klavochka": "Counting up high, my dear ⬆️"}),

    lesson(32, "Numbers right: 6-0 at speed",
           "Right-hand digits — same fingers as Y-U-I-O-P",
           58, "6 7 8 9 0 67 78 89 90 06 16 27 38 49 50 67890 09876 66778 88990",
           ["6","7","8","9","0","Space"],
           "Right number row",
           ["6 = right index, 0 = right pinky",
            "Mirror the QWERTY logic",
            "Stretch UP, return to home row immediately"],
           {"anna": "Right side digits. Same logic — column = finger.",
            "maxim": "All 10 digits at speed now. Mixed text next.",
            "knopych": "🔢 RIGHT DIGITS! 6-0 same fingers as YUIOP!",
            "klavochka": "Counting all the way to ten, my sunshine ⭐"}),

    lesson(33, "Dates and time chat",
           "Quick date/time messages",
           60, "see you at 3 today meet at 4:30 the show starts at 8 PM on June 15 my flight at 9:45 AM tomorrow at noon sharp",
           ["A-Z","0-9","Shift","Space",":","."],
           "Numbers + times + AM/PM",
           ["Real chat format: \"3 today\" or \"8 PM tomorrow\"",
            "Colon for time format",
            "Numbers should flow as fast as letters by now"],
           {"anna": "Real chat format. Dates + times = daily life.",
            "maxim": "Time-and-date prose is high-frequency. Drill it.",
            "knopych": "📅 CALENDAR MODE! Days and times in flow!",
            "klavochka": "Making plans with friends, my dear 📆"}),

    lesson(34, "Hashtags and mentions",
           "Social media symbols — # and @ at speed",
           62, "#fyp #foryou #vibes #2026 #goals @user @friend @mod #throwback #monday #squad #life #love @official",
           ["A-Z","0-9","Shift","Space","#","@"],
           "# and @ symbol drill",
           ["# is Shift+3, @ is Shift+2",
            "Both need RIGHT pinky Shift + LEFT hand reach",
            "These two symbols = 90% of social media posts"],
           {"anna": "# and @ are everywhere online. Master both = master social.",
            "maxim": "Two symbols cover 90% of social media. Worth the drill.",
            "knopych": "📱 # AND @ POWER! Social media engaged!",
            "klavochka": "Like little signs pointing to friends and ideas, my dear 💕"}),

    lesson(35, "Twitter-style short posts",
           "Punchy short-form posts",
           63, "ok but why is everyone sleeping on this anyway just dropped my new playlist link in bio fr fr go check it out",
           ["A-Z","Space"],
           "Short post rhythm",
           ["Twitter/X posts are short and punchy",
            "No punctuation = pure word rhythm",
            "Lowercase intentional — modern teen style"],
           {"anna": "Twitter rhythm. Short, punchy, lowercase intentional.",
            "maxim": "Short-form is the dominant content format. Drill it.",
            "knopych": "🐦 TWEET MODE! Quick and snappy!",
            "klavochka": "Quick little messages, my sunshine 💬"}),

    lesson(36, "Rhythm: social feed flow",
           "Scroll through multiple short posts at sustained tempo",
           65, "live laugh log on grind never stop monday energy hits different fr no thoughts head empty good vibes only literally me",
           ["A-Z","Space"],
           "Social feed rhythm",
           ["Multiple meme phrases back to back",
            "Find the social-media-scroll rhythm",
            "Metronome at 65 BPM — match it"],
           {"anna": "Social feed style at 65 WPM. Pure modern rhythm.",
            "maxim": "Scrolling = pattern recognition. Type like you read.",
            "knopych": "📲 SCROLL MODE! Meme after meme!",
            "klavochka": "Modern poetry, my dear — short and sweet 🌸"},
           phase=3, rhythm=True),

    lesson(37, "Instagram caption style",
           "Captions with punctuation + hashtags",
           65, "sunset vibes never get old. cant wait for summer. blessed and grateful. coffee first, talk later. #goals #mood #weekend",
           ["A-Z","Space",",",".","#"],
           "Caption rhythm + hashtags",
           ["Captions = short sentences + hashtag cluster",
            "Period or no period — both common",
            "Hashtag cluster at end is the standard format"],
           {"anna": "Instagram captions follow a rhythm: thought + thought + hashtags.",
            "maxim": "Photo captions = quick prose. High-volume daily writing.",
            "knopych": "📸 CAPTION FLOW! Picture + words!",
            "klavochka": "Sharing a moment with words, my treasure ✨"}),

    lesson(38, "ASCII emoji and reactions",
           "Old-school emoticons + reaction phrases",
           66, ":) :D :( ;) <3 :P xD =) :') no way!! lol haha lmao bruh wait what omg fr cap nope yikes mood",
           ["A-Z","Shift","Space",":",";",")","(","<","3","=","'",",","!"],
           "Symbol + word mix",
           ["ASCII emoji = colon + paren or related",
            "Speed comes from chunking — :) = one motion",
            "Reactions = high-frequency social vocab"],
           {"anna": "ASCII emoticons predate emoji. Still everywhere in chat.",
            "maxim": "Symbol clusters = chord-like motions. Train them as units.",
            "knopych": ":) :D <3 PRE-EMOJI ART!",
            "klavochka": "Tiny faces made from punctuation, my dear 😊"}),

    lesson(39, "Reddit/forum comment style",
           "Long-form comment with quotes and reactions",
           67, "honestly this is the best take i've seen all week. \"facts only\" hits different. anyone else feel like 2026 is moving way too fast?",
           ["A-Z","Space",".",",","\"","'","?"],
           "Comment-style prose",
           ["Forum comments are mid-length, conversational",
            "Quotes inside prose appear often",
            "Apostrophes (i've, don't) are constant"],
           {"anna": "Reddit-style is conversational with quotes. Train both.",
            "maxim": "Comments are the most-typed format online. Master them.",
            "knopych": "💬 COMMENT THREAD! Reply game on point!",
            "klavochka": "Sharing thoughts in conversation, my dear 🗨️"}),

    lesson(40, "Teen milestone: 40 lessons",
           "Mid-Teen-course checkpoint at 68 WPM",
           68, "forty lessons in and your speed is double what it was on day one — that is real progress. keep showing up; the second half is where things really click into place.",
           ["A-Z","Space",",",".","-",";"],
           "40-lesson speed gate",
           ["40 lessons = halfway through teen course",
            "Track your peak WPM here",
            "Block 4 brings pure speed sprints next"],
           {"anna": "🎯 40 lessons in. Track your number — Block 4 will push it higher.",
            "maxim": "Halfway through. Pace yourself, but don't lose the gain.",
            "knopych": "🏔️ HALFWAY CHECKPOINT! Climb continues!",
            "klavochka": "Halfway there, my star ⭐⭐ Beautiful!"}),

    lesson(41, "URLs and links",
           "URL format + slashes + dots",
           68, "tiktok.com/@user youtube.com/watch?v=abc123 spotify.com/playlist insta.com/p/post123 twitch.tv/user discord.gg/server",
           ["A-Z","0-9","Space",".","/",":","?","=","@"],
           "URL structure at speed",
           ["URLs = dot + slash + symbol mix",
            "= and ? appear in query strings",
            "Practice this — modern life IS URLs"],
           {"anna": "URLs are everywhere. Master the slash + dot rhythm.",
            "maxim": "Most workers type 50+ URLs a day. High-payoff drill.",
            "knopych": "🔗 LINK MODE! URLs at speed!",
            "klavochka": "Tiny paths to places, my dear 🌐"}),

    lesson(42, "TikTok-style commentary",
           "Quick observational posts with capitals for emphasis",
           69, "Bro the way she just stared into the camera. THAT was the look. POV: you finally figured it out. Wait until the end. No because actually that hit.",
           ["A-Z","Shift","Space",".",",",":"],
           "Mixed capital emphasis + commentary",
           ["ALL CAPS for emphasis (THAT) — Shift+letter+letter",
            "POV format is teen-native",
            "Capital snippets in lowercase prose"],
           {"anna": "Modern teen prose mixes caps for emphasis. Capture both rhythms.",
            "maxim": "Generation-Z writing pattern. Real-life applied training.",
            "knopych": "🎬 TIKTOK STYLE! POV and reaction commentary!",
            "klavochka": "The way teens write today, my sunshine 💫"}),

    lesson(43, "Rhythm: chat conversation flow",
           "Back-and-forth chat at sustained tempo",
           70, "hey what time at 7 cool bring snacks ok which ones the spicy ones obvi sounds good see you then bye bye drive safe",
           ["A-Z","Space"],
           "Chat back-and-forth rhythm",
           ["Real chat = short bursts, no punctuation",
            "Multiple speakers in one line",
            "Metronome at 70 BPM"],
           {"anna": "Chat rhythm. Short bursts, no punctuation, full speed.",
            "maxim": "Chat is the most-typed format of all. Master the rhythm.",
            "knopych": "💬 CHAT FLOW! Quick fire convo!",
            "klavochka": "Friends talking back and forth, my treasure 💕"},
           phase=3, rhythm=True),

    lesson(44, "Pre-final: high-density social",
           "Mixed real-world content — pre-final warmup",
           70, "OMG the new album just dropped 🎵 #blessed — link in bio: spotify.com/album/2026. Tag @bestie if you're crying too 😭. Drop your fav track below!",
           ["A-Z","0-9","Shift","Space",".",",","!","#","@","/",":","-","'"],
           "All content classes mixed",
           ["Letters + numbers + URLs + hashtags + mentions",
            "Real teen social post density",
            "Last warmup before final"],
           {"anna": "Real teen social post. All character classes mixed.",
            "maxim": "Pre-final density test. Pass = ready for BLOCK 3 FINAL.",
            "knopych": "📱 SOCIAL OVERLOAD! All the things at once!",
            "klavochka": "Modern way of sharing joy, my dear 🎉"}),

    lesson(45, "BLOCK 3 FINAL: Social media mastery",
           "Block 3 final — 70 WPM on a realistic social media post",
           70, "Tournament day! 🏆 We're live at 6 PM on twitch.tv/squad-2026 with the full lineup: @ace, @nova, @blaze. Drop a follow if you want to play with us next week — we're recruiting one more spot. Catch you all live!",
           ["A-Z","0-9","Shift","Space",".",",","!","#","@","/",":","-","'"],
           "Block 3 mastery gate at 70 WPM",
           ["🎓 Teen Block 3 done! 70 WPM on social content = elite teen typing",
            "Block 4 next: pure speed sprints",
            "Last finale: L75 at 90 WPM on real-world prose"],
           {"anna": "🎯 Teen Block 3 done! 70 WPM on social. Block 4 = pure speed.",
            "maxim": "Social media mastery cleared. Speed lab opens in Block 4.",
            "knopych": "🐉🏆 BLOCK 3 BOSS DOWN! Social tier achieved!",
            "klavochka": "Three triumphs, my hero! 🎉⭐⭐⭐ Two blocks to go!"},
           error_pct=5),
]


for d in LESSONS:
    fp = OUT / f'lesson_{d["lesson_number"]}.json'
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    print(f'  wrote en_teen/lesson_{d["lesson_number"]}.json ({d["text_length"]} chars, WPM {d["target_wpm"]})')

print(f'\nDone. {len(LESSONS)} Teen B3 lessons generated.')
